services:
  - type: web
    name: mediapipe-app
    env: python
    pythonVersion: 3.11
    buildCommand: python -m pip install --upgrade pip && python -m pip install -r requirements.txt
    startCommand: python app.py
